-- phpMyAdmin SQL Dump
-- version 4.7.9
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1:3306
-- Generation Time: Oct 29, 2019 at 12:33 AM
-- Server version: 5.7.21
-- PHP Version: 7.2.4

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET AUTOCOMMIT = 0;
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `asus`
--

-- --------------------------------------------------------

--
-- Table structure for table `products`
--

DROP TABLE IF EXISTS `products`;
CREATE TABLE IF NOT EXISTS `products` (
  `product_id` int(11) NOT NULL AUTO_INCREMENT,
  `product_name` varchar(256) NOT NULL,
  `product_description` text NOT NULL,
  `product_category` varchar(50) NOT NULL,
  `product_type` varchar(50) NOT NULL,
  `product_image` varchar(256) NOT NULL,
  `product_price` float NOT NULL,
  PRIMARY KEY (`product_id`)
) ENGINE=MyISAM AUTO_INCREMENT=51 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `products`
--

INSERT INTO `products` (`product_id`, `product_name`, `product_description`, `product_category`, `product_type`, `product_image`, `product_price`) VALUES
(1, 'ASUS ZenBook Pro UX550UD 15.6\" Full HD Gaming Laptop', 'ZenBook Pro is designed to entice you with pure, unadulterated power. Power to create your dreams. Power to fuel your imagination. Power to do whatever you want to do, anywhere and everywhere. Every part of ZenBook Pro has been crafted to make it faster, more powerful and more amazing than the previous generation from its 7th Generation Intel Core i7 processor to its gaming-grade NVIDIA GeForce GTX 1050 graphics and quad-speaker Harman Kardon surround-sound audio. And every detail of its finish makes it even more beautiful than ever before including its precision-engineered solid-aluminum unibody and stunning FHD NanoEdge display. The new ZenBook Pro is not just better: its the best.', 'notebooks', 'zenbook', 'zenbook-pro.jpg', 1323.99),
(2, 'ASUS ZenBook 3 Deluxe UX490UAR 14\" Full HD Laptop', 'They say that you can\'t improve on perfection. That\'s a nice thought, but with the new ZenBook 3 Deluxe we\'ve proved them wrong by taking the amazing ZenBook 3 and making it even better. ZenBook 3 Deluxe achieves the almost-impossible, featuring a gorgeous 14-inch display in an elegant and compact chassis that\'s no bigger than many 13-inch laptops. It\'s an unrivaled combination of power and beauty, giving you the perfect balance between portability and productivity. Measuring just 12.9mm thin and weighing only 1.1kg, ZenBook 3 Deluxe has everything you need for superb on-the-go performance, including a 7th Generation Intel Core i7 processor, 512GB PCIe SSD, two USB Type-C (USB-C) ports with Full HD display supports, and a powerful quad-speaker audio system. ZenBook 3 Deluxe takes ZenBook 3 to the next level for the ultimate prestige and performance.', 'notebooks', 'zenbook', 'zenbook-3-deluxe.jpg', 1222.99),
(3, 'ASUS Zenbook Flip S UX370UA 13.3\" Convertible Laptop ', 'ASUS ZenBook Flip S is one of the worlds thinnest and lightest convertible laptops, designed for anywhere and everywhere. It combines elegant sophistication with the convenience and versatility of a 360-flippable display. This ultra-thin, ultra-light convertible is a stylish laptop, a handy tablet or anything in between. Its Intel Core i7 processor lets you sail through everyday computing tasks with ease. And it supports a stylus, so its your perfect partner for Windows 10!', 'notebooks', 'zenbook', 'zenbook-flip-s.jpg', 1487.49),
(4, 'ASUS ZenBook UX410UA 14\" Full HD Light Weight Laptop ', 'The all-new ZenBook UX410 brings you elegance, sophistication and superb performance in a gorgeously slim and light design. Crafted from solid aluminum and featuring our iconic spun-metal Zen-inspired finish, ZenBook UX410 is a mere 18.95mm thin. And its travel-friendly weight of just 1.4kg means taking it with you is never a burden, and using it is always a pleasure with its crisp, clear 14-inch wide viewing angle display and 6mm slim bezel. Featuring the latest generation of Intel Core processors, powerful graphics and super-fast storage, ZenBook UX410 is no slouch, either it has all the performance you need to blitz through your working day. ZenBook UX410 makes everything easier, in style.', 'notebooks', 'zenbook', 'zenbook-ux410.jpg', 853.99),
(5, 'ASUS ZenBook UX310UA 13.3\" Full HD Light Weight Laptop ', 'The all-new ZenBook UX310 brings you elegance, sophistication and superb performance in a gorgeously slim and light design. Crafted from solid aluminum and featuring our iconic spun-metal Zen-inspired finish, ZenBook UX310 is a mere 18.35mm thin. And its travel-friendly weight of just 1.4kg means taking it with you is never a burden, and using it is always a pleasure with its crisp, clear 13.3-inch wide viewing angle display. Featuring the latest 6th-generation Intel Core i7 Processor, super-fast storage, ZenBook UX310 is no slouch, either it has all the performance you need to blitz through your working day. ZenBook UX310 makes everything easier, in style.', 'notebooks', 'zenbook', 'zenbook-ux310.jpg', 960.99),
(6, 'ASUS ZenBook UX330UA 13.3\" Light Weight Laptop ', 'The new ZenBook UX330 is simply breathtaking. Its supremely elegant aluminum-alloy unibody chassis is an unbelievable 13.5mm thin, and weighs a feather-light 1.2kg. And with up to 12 hours battery life, ZenBook UX330 takes even the longest working day in its stride. The numbers may be impressive, but its looks are even more so, with the stunning Zen-inspired spun-metal finish available in your choice of stylish Rose Gold or sophisticated Quartz Grey. ZenBook UX330 has more than enough performance to cope with all your on-the-go productivity needs, with a powerful 6th-generation Intel Core up to i7 processor. The wide-viewing-angle display is a real treat for your eyes too, with its pin-sharp up to 3200 by 1800 resolution enhanced by exclusive ASUS Splendid and ASUS Tru2Life technologies for vivid, lifelike colors and clear, sharp videos.', 'notebooks', 'zenbook', 'zenbook-ux330.jpg', 728.49),
(7, '\r\nASUS VivoBook Pro N580VD 15.6\" Gaming Laptop', 'The ASUS VivoBook Pro 15 is a slim and lightweight high-performance laptop thats powered by a 7th Generation Intel Core processor. It features a FHD display, high-quality NVIDIA GeForce GTX 1050 gaming-grade graphics, audio co-developed by Harman Kardon, and the latest cooling and fast-charge technologies.', 'notebooks', 'vivobook', 'vivobook-pro.jpg', 1054.49),
(8, 'ASUS VivoBook S15 S510UQ 15.6\" Gaming Laptop ', 'The ASUS VivoBook S15 gives you the perfect combination of beauty and performance. With its slim NanoEdge bezel, brushed-metal finish, the latest Intel Core i3 Processor and 8GB RAM, VivoBook S15 is designed for today\'s fast-paced urban lifestyle.', 'notebooks', 'vivobook', 'vivobook-s15.jpg', 959.49),
(9, 'ASUS VivoBook S14 S410UA 14\" Light Weight Laptop', 'ASUS VivoBook S14 provides boundless productivity for people on the go. Its compact and lightweight design has an 18.8mm profile with an overall weight of just 1.43 kg. VivoBook S14 delivers uncompromising performance, it\'s powered by up to the latest Intel Core i3 processor. It also offers a 14-inch NanoEdge display in a frame size that\'s typical of smaller, 13-inch laptops.', 'notebooks', 'vivobook', 'vivobook-s14.jpg', 565.49),
(10, 'ASUS VivoBook Max X541UA 15.6\" Multimedia Laptop', 'ASUS VivoBook Max Series laptops are designed to give you a truly immersive multimedia experience. Powered by a 6th-generation Intel Core processor, gaming-grade NVIDIA GeForce graphics, and exclusive SonicMaster audio incorporating ICEpower technology, VivoBook Max Series gives you outstanding audiovisuals ever experienced on a laptop.', 'notebooks', 'vivobook', 'vivobook-max.jpg', 562.99),
(11, 'ASUS VivoBook Flip TP401CA 14\" Convertible Laptop', 'ASUS VivoBook Flip 14 is the slimmest and lightest 14-inch model in the ASUS VivoBook Flip range. It has an incredibly-slim 0.6 inch profile, and features the ASUS NanoEdge ultra-narrow display bezel that enables it to fit 14-inch display into a chassis of an average 13-inch laptop. It\'s powered by up to an Intel Core i7 processor for the performance required for daily multitasking and entertainment.Use VivoBook Flip 14 as a stylish laptop, a handy tablet, or anything in between.', 'notebooks', 'vivobook', 'vivobook-flip.jpg', 595.49),
(12, '\r\nASUS VivoBook E12 E203NA 11.6\" Mini Laptop', 'The ASUS VivoBook E12 is designed to help you be productive all day even when youre on the move. This compact and lightweight 11.6-inch laptop is powered by the latest Intel processor and provides up to 10 hours of battery life. And with pre-loaded Windows 10, it offers full compatibility with a wide range of software and peripherals. It\'s the best laptop for people on the go.', 'notebooks', 'vivobook', 'vivobook-e12.jpg', 210.99),
(13, 'ASUS Chromebook C202SA 11.6\" Light Weight Laptop', 'The ASUS Chromebook C202 is the ideal education computer for every school IT manager, student, and teacher. With its classroom ruggedness, the ASUS Chromebook C202 is developed to meet the daily rigors and intense usage by students both inside and outside of the classroom. Beyond its rugged construction, the ASUS Chromebook C202 is also designed for easy maintenance to minimize downtime. The result is a Chromebook which is designed for maximum usage, creating more learning opportunities for students.', 'notebooks', 'chromebooks', 'chromebook-11.jpg', 251.99),
(14, 'ASUS Chromebook Flip C302CA 12.5\" Full HD Laptop', 'The slim, light and incredibly stylish Chromebook Flip C302 combines the simplicity of Chromebook with powerful components and an amazing 360 hinge that lets you flip instantly between a high-performance Chromebook, a handy Chromebook tablet, or anything in between! This versatile touchscreen device frees you to work or play anywhere, anytime with its 10-hour battery life, backlit keyboard with a spacious 104.5mm x 61mm touchpad, and lightning-fast USB-C port. Chromebook Flip C302 gives access to thousands of amazing productivity apps available at Chrome Web Store. The Chromebook will also support Android apps on Google Play in the future.', 'notebooks', 'chromebooks', 'chromebook-flip.jpg', 674.99),
(15, 'ASUS Chromebook 13.3\" Light Weight Laptop', 'The incredibly sleek and light Chromebook C300 is designed to go everywhere you want to go. Weighing just 1.35kg, it won\'t cramp your mobile lifestyle, and its stylish looks will make you the centre of attention. To add a touch of your own personality, with Chromebook C300 you can choose one of the gorgeously smooth and tactile Hot Red and Fresh Blue shades, or opt for the sophisticated brushed texture of Cool Black.', 'notebooks', 'chromebooks', 'chromebook-13.jpg', 174.99),
(16, 'ASUS ROG GL702VS 17.3\" Gaming Laptop', 'Experience unmatched performance with ROG Strix GL702\'s 6th-generation Intel Core i7 quad-core processor combined with a discrete NVIDIA GeForce GTX 1070 graphics with full Microsoft DirectX 12 support. The latest hardware gives you efficient, powerful performance for heavy gaming or productive multitasking such as live streaming and video editing.', 'notebooks', 'gaming', 'gaming-rog.jpg', 1817.99),
(17, 'ASUS ROG Strix GL502VS 15.6\" Gaming Laptop ', 'ROG Strix GL502 packs the latest 7th-generation Intel Core i7 processor and NVIDIA GeForce 1070 GTX graphics in a compact and lightweight design, fully equipped with a stunning 120 Hz G-SYNC panel. ROG Strix GL502 enables users to enjoy high-end gaming from anywhere.', 'notebooks', 'gaming', 'gaming-rog-strix-gl50.jpg', 1632.99),
(18, 'ASUS ROG Strix GL702Z 17.3\" Gaming Laptop', 'ROG Strix GL702ZC is the world\'s first gaming laptop featuring the AMD Ryzen 7 processor. Combining the sheer power of AMD\'s revolutionary Ryzen platform with ROG\'s gaming design legacy, ROG Strix GL702ZC is designed to deliver amazing performance to satisfy the needs of hard-core gamers and users with demanding, multimedia-heavy workloads. With a 17-inch, wide-view panel for incredible visuals, an anti-ghosting backlit keyboard for fast, accurate control, and ROG Gaming Center with a wealth of gamer-oriented features, ROG Strix GL702ZC is a finely tuned weapon backed by eight-core power for gaming a competitive edge.', 'notebooks', 'gaming', 'gaming-rog-strix.jpg', 1179.49),
(19, 'ASUS ZenPad 8.0 Z380M 8\" Quad-Core Tablet ', 'The design of ASUS ZenPad 8.0 carries modern influences and a simple, clean look that gives it a universal and stylish appeal. These elements are inspired by our Zen design philosophy of balancing beauty and strength. ASUS ZenPad 8.0 is an 8-inch tablet with a 76.5% screen-to-body ratio an incredible engineering achievement made possible by reducing the bezel width to the bare minimum.', 'tablets', 'zenpad', 'zenpad-8.jpg', 151.99),
(20, 'ASUS ZenPad 10 Z301M 10.1\" Tablet', 'The all-new ASUS ZenPad 10 fuses the latest technology with a fashionable, modern design featuring clean lines and embossed knit-patterning for a tablet that delivers incredible entertainment experiences and stylish appeal. The all-new ASUS ZenPad 10 fuses the latest technology with a fashionable, modern design featuring clean lines and embossed knit-patterning for a tablet that delivers incredible entertainment experiences and stylish appeal.', 'tablets', 'zenpad', 'zenpad-10.jpg', 172.49),
(21, 'ASUS ZenPad Z301M 10.1\" Tablet', 'The all-new ASUS ZenPad 10 fuses the latest technology with a fashionable, modern design featuring clean lines and embossed knit-patterning for a tablet that delivers incredible entertainment experiences and stylish appeal. The all-new ASUS ZenPad 10 fuses the latest technology with a fashionable, modern design featuring clean lines and embossed knit-patterning for a tablet that delivers incredible entertainment experiences and stylish appeal.', 'tablets', 'zenpad', 'zenpad-v30.jpg', 174.49),
(22, 'ASUS ZenFone 4 Unlocked Smartphone 5.5\" Display', 'ZenFone 4 is a 5.5-inch smartphone that evolves the ZenFone lineage with luxurious, crafted design and delivers an unparalleled mobile photography experience with a dual-lens camera system featuring the flagship Sony IMX362 image sensor, a large F1.8 aperture lens and a 120 wide-angle lens. The latest powerful and energy-efficient Qualcomm Snapdragon 660/630 Mobile Platform provides performance for every scenario and a high-capacity 3300mAh lithium polymer battery coupled with ASUS BoostMaster fast-charging technology keeps ZenFone 4 going longer.', 'phones', 'zenfone', 'zenphone-4.jpg', 419.99),
(23, 'ASUS ZenPower Ultra 20100 MAh Power Bank With Integrated LED Flashlight - Black', 'Luxury, high-capacity PowerBank from Asus with the name ASUS ZenPower Ultra 20100 mAh . An excellent companion that will not leave you in the lurch in the absence of juice. You know, you go on vacation, trip or cottage and do not want to unnecessarily stress the fact that your phone does not zrovinka energy. And here, in this moment comes the Asus Zen Power. PowerBank battery has a capacity of 20,100 mAh . You can be so sure that will be sufficient to complete the acquisition multiple of your smartphone or tablet. One of its outstanding features is that it has a pair of USB ports with Quick Charge function. This feature is marking as rapid.', 'phones', 'zenpower', 'zenpower-ultra.jpg', 54.99),
(24, '\r\nASUS ZenFone 4 Max Unlocked Smartphone 5.5\" Display', 'ASUS ZenFone 4 Max is a smartphone designed to go the distance and accompany you on all of lifes adventures. Its high capacity 5000mAh battery with advanced power management and dual cameras keeps up with your active lifestyle and is always at the ready to capture extraordinary moments. The 120 wide-angle camera on ZenFone 4 Max has a 200% larger field of view than standard smartphone cameras, so you can fit more scenery and people in the frame for dramatic photos and videos that capture a true sense of place. When taking photos indoors, the wide-angle view makes it much easier to get the shot you want especially in confined spaces where it may not be possible to take a few steps back to fit everyone and everything into the photo. The unique perspective of the wide-angle lens can also be used to stylistic effect, allowing you to exaggerate the sense of space in any setting to capture more dramatic scenes and stunning, expansive landscapes.', 'phones', 'zenfone', 'zenphone-4-max.jpg', 205.49),
(25, 'ASUS ZenFone 4 Max 5.5-Inch Unlocked 4G Smartphone', 'ASUS ZenFone 4 Max is a smartphone designed to go the distance and accompany you on all of lifes adventures. Its high capacity 5000mAh battery with advanced power management and dual cameras keeps up with your active lifestyle and is always at the ready to capture extraordinary moments. The 120 wide-angle camera on ZenFone 4 Max has a 200% larger field of view than standard smartphone cameras, so you can fit more scenery and people in the frame for dramatic photos and videos that capture a true sense of place. When taking photos indoors, the wide-angle view makes it much easier to get the shot you want especially in confined spaces where it may not be possible to take a few steps back to fit everyone and everything into the photo. The unique perspective of the wide-angle lens can also be used to stylistic effect, allowing you to exaggerate the sense of space in any setting to capture more dramatic scenes and stunning, expansive landscapes.', 'phones', 'zenfone', 'zenphone-4-max-white.jpg', 254.49),
(26, 'ASUS ZenFone 4 Unlocked 4G LTE Smartphone 5.5-Inch Display', 'ZenFone 4 is a 5.5-inch smartphone that evolves the ZenFone lineage with luxurious, crafted design and delivers an unparalleled mobile photography experience with a dual-lens camera system featuring the flagship Sony IMX362 image sensor, a large F1.8 aperture lens and a 120 wide-angle lens. The latest powerful and energy-efficient Qualcomm Snapdragon 660/630 Mobile Platform provides performance for every scenario and a high-capacity 3300mAh lithium polymer battery coupled with ASUS BoostMaster fast-charging technology keeps ZenFone 4 going longer.', 'phones', 'zenfone', 'zenphone-4-white.jpg', 450.99),
(27, 'ASUS MG279Q 27\" Quad HD Widescreen LED Monitor', 'The MG279Q gaming display is built for victory in the professional gaming arena, and features a WQHD panel with a 144Hz refresh rate and wide viewing angles. Its ergonomic design, together with Flicker-Free and Ultra Low Blue Light technology, ensure you stay comfortable during those marathon gaming sessions. ', 'peripherals', 'monitors', 'mg279q.jpg', 602.99),
(28, 'ASUS MX299Q 29\" IPS Black,Silver Monitor', 'A masterful culmination of advanced technology and artistic design, Designo Series MX299Q Ultra-wide 21:9 Cinematic monitor represents the current state of the art in PC monitors. A sleek 29-inch AH-IPS A+ display with an ultra-wide 21:9 ratio and 2560 by 1080 resolution, MX229Q delivers a 33% larger display area compared to a Full HD monitor for the best theater-like home entertainment. Whats more, MX299Q has an edge-to-edge, frameless cinematic display for an ideal multi-display setup and stylish design.', 'peripherals', 'monitors', 'mx299q.jpg', 406.49),
(29, 'ASUS ROG SWIFT PG248Q 24\" Full HD Widescreen LED Gaming Monitor', 'ROG Swift PG248Q is a competition-grade gaming monitor that gives you seamless visuals and super-smooth gameplay. It features a 24-inch Full HD (1920 x 1080) panel with a 16:9 aspect ratio. Its NVIDIA G-SYNCTM-ready too. ROG Swift PG248Q boasts an overclockable 180Hz refresh rate and 1ms gray-to-gray (GTG) response time to eliminate screen tearing and choppy frame rates.', 'peripherals', 'monitors', 'rog-swift.jpg', 509.99),
(30, 'ASUS ROG SWIFT PG348Q 34\" UltraWide Curved LED Gaming Monitor', 'The new flagship of the ROG monitor fleet, the Swift PG348Q expands your scope, allowing faster target acquisition while increasing immersive visuals with a 34-inch 3440x1440 curved ultra-wide IPS panel. Bristling with advanced display tech, the newest Swift PG348Q also features NVIDIA G-SYNC technology for smooth and seamless gameplay, while simultaneously sporting a 100Hz refresh rate, eliminating roadblocks between your skill and victory. Add the armored design and unique ASUS features and you\'re looking at a monitor that is truly unrivaled.', 'peripherals', 'monitors', 'rog-swift-ultrawide-curved.jpg', 1180.49),
(31, 'ASUS VC279H 27\" Monitor LED IPS', 'VC279 series feature with In-Plane Switching technology panel with a 178 wide-view angle that minimizes color shift on both horizontal and vertical planes to ensure quality visuals from almost any direction. With ASUS Smart Contrast Ratio (ASCR) of 80,000,000:1 and 250cd/m brightness, VC279H augments display contrast and sharpness by adjusting backlighting luminance to achieve the deepest blacks and brightest whites for truly lifelike visuals', 'peripherals', 'monitors', 'vc279h.jpg', 205.49),
(32, 'ASUS VP278H 27\" Full HD Gaming Monitor', 'VP278H 27\" Full HD monitor with 100,000,000:1 high contrast ratio, ASUS-exclusive SplendidPlus and VivdPixel technologies is optimized for the finest image and color quality. This approach extends to the study stand and slim profile without compromising style in ensuring stability and durability. 1ms (GTG) quick response time eliminates ghosting and tracers for more fluid video playback.', 'peripherals', 'monitors', 'vp278h.jpg', 179.49),
(33, 'ASUS ROG Strix Wireless Gaming Headset With 7.1 Surround For PC/PS4/Xbox/Mac', 'ROG Strix Wireless is a gaming headset with 2.4GHz wireless technology that provides a lower-latency connection than Bluetooth headsets for instant audio transmission. The included USB dongle features exclusive technology that enables wireless connections to both PC and PlayStation 4 with fully functional headset controls. With ROG Strix Wireless, every in-game sound reaches your ears instantly even from up to 15 meters away from your PC.', 'peripherals', 'headsets', 'rog-strix.jpg', 112.49),
(34, 'ASUS ROG Orion Gaming Headset With Big 50mm Drivers For PC/PS4/Xbox/Mac/Mobile Devices', 'The Orion full-size gaming headset is designed to provide gaming enthusiasts with the finest audio immersion and positioning needed in any game and at any location. After extensive research and development and taking customer feedback into account, the ROG team concluded that user comfort is key when it comes to gaming headsets. As such, ROG Orion possesses 100mm over-ear cushions for greater comfort, and bring immersive audio with large 50mm neodymium drivers.', 'peripherals', 'headsets', 'rog-orion.jpg', 81.99),
(35, 'ASUS ROG Strix Fusion 300 Gaming Headset With Microphone For PC/Mobile/Console', 'ROG Strix Fusion 300 gaming headset features an exclusive airtight chamber design and 50mm ASUS Essence drivers, delivering pure gaming audio with deep bass. Immerse yourself in rich sound with onboard 7.1-channel virtual surround-sound wherever you go - no dongles or extra software are needed! Strix Fusion 300 is lightweight and comfortable, and has wide compatibility with PC, Mac and game consoles. Experience impeccable, fully-immersive gaming audio with Strix Fusion 300!', 'peripherals', 'headsets', 'rog-strix-fusion.jpg', 117.99),
(36, 'ASUS ROG Gladius II Origin Ergonomic Wired Optical Gaming Mouse', 'Get ready to lock your target and embrace victory with the ROG Gladius II Origin optical gaming mouse, the third in the Gladius family. The Gladius II Origin has an advanced 12000 DPI optical sensor for fast response and precise control, ergonomic right-handed design to ensure you stay comfortable during extended gaming sessions and Aura Sync lighting technology to outshine the competition.', 'peripherals', 'mice', 'rog-gladius-2.jpg', 86.49),
(37, 'ASUS ROG Pugio Truly Ambidextrous Optical Gaming Mouse', 'ROG Pugio is an ambidextrous gaming mouse that offers ultimate customisability to meet the needs of the most hardcore gamers. Its configurable side buttons let you decide on your own side button layout, while exclusive push-fit switch sockets offer variable click resistance. The push-fit design makes it easy to replace worn out switches to extend the lifespan of the mouse. The Pugio features stunning, aggressive aesthetics to match its performance including angular ASUS Aura RGB light channels with Aura Sync support.', 'peripherals', 'mice', 'rog-pugio.jpg', 76.99),
(38, 'ASUS ROG Sica White Ergonomic Ambidextrous Optical MOBA Gaming Mouse Co-Designed With Pro-Gamers For All Grip Types', 'ROG Sica is crafted to withstand the demands of marathon MOBA gaming, and is designed with input from pro-gaming teams like Taipei Assassins. This ambidextrous 5000 DPI optical gaming mouse optimizes click responsiveness by having the buttons independent of the mouse body, and is especially suited for those with a fingertip grip. ROG Sica\'s exclusive easy-swap switchable socket design even lets you customize click resistance, and it features upgraded Omron switches with 20-million-click durability. The latest ROG Sica features a glossy Glacier White finish. ROG makes sure you get the most out of your games.', 'peripherals', 'mice', 'rog-sica.jpg', 39.49),
(39, 'ASUS ROG Spatha Rechargeable Wireless MMO Gaming Mouse', 'ROG Spatha has a total of 12 programmable buttons, including six thumb buttons, to give you intuitive command and control. It fits perfectly in your hand, and has been ergonomically-designed to give you tactile feedback and response. Gaming mouse buttons take a lot of punishment, and that\'s why the buttons on ROG Spatha feature durable Omron switches with a 20-million-click lifespan. The exclusive switchable socket design allows for easy customization too.', 'peripherals', 'mice', 'rog-spatha.jpg', 145.49),
(40, 'ASUS WT425 Wireless Optical Mouse White', 'Perfect fit mouse design goes easy on your hands for total comfort and prolonged use whether productive or sheer entertainmentThe ASUS WT425 Optical Wireless Mouse features advanced tracking technology with resolutions of up to 1600DPI. A dedicated switch lets you easily select sensitivity levels of 1000 and 1600DPI; while its silent mouse click design means you can use it in quiet environments.Its ergonomic too, with a tactile, easy-grip coating ensuring your comfort even after long periods of use.', 'peripherals', 'mice', 'wt425.jpg', 23.99),
(41, 'ASUS WT465 Wireless Optical Mouse Black', 'Subtle looks hold the secret to a full spectrum of mouse capabilities. Perfect for every application from productivity to gaming and for any PC from Ultrabooks to desktops, this wireless enabler gives you a neat product with numerous features. It uses smart power management to keep battery life extended, and can go up to 1600dpi precision with switchable resolutions you control. The transceiver is extra-compact so you can leave it connected to your notebook PC and go, or tuck it into the mouse for even more space-saving convenience. Get your hands on the one mouse for all your needs!', 'peripherals', 'mice', 'wt465.jpg', 20.49),
(42, 'ASUS CERBERUS MECH RGB Backlit Mechanical Gaming Keyboard ', 'ASUS Cerberus Mech RGB is the latest gaming keyboard in the award-winning Cerberus series. Built to satisfy avid gamers\' needs, Cerberus Mech RGB was designed with loads of high-performance features, including durable, 70-million-keystroke-lifespan mechanical switches that stand up to the most intense action, and dedicated hot keys for executing macros and more while gaming. Customizable RGB backlighting effects shine in millions of vivid colors, letting you tailor Cerberus Mech RGB to your own individual style.', 'peripherals', 'keyboards', 'cerberus.jpg', 125.49),
(43, 'ASUS ROG Claymore Core RGB Mechanical Gaming Keyboard', 'Individually-backlit keys with ASUS Aura RGB synchronization for unlimited personalization options. Fully programmable keys with on the fly macro recording. 100% anti-ghosting with N-key rollover (NKRO) technology. Compact aluminum construction with Mayan detailing for extreme aesthetics and durability', 'peripherals', 'keyboards', 'rog-claymore.jpg', 163.99),
(44, 'ASUS ROG STRIX FLARE Mechanical RGB Gaming Keyboard', 'Flare up your game with ROG Strix Flare a mechanical gaming keyboard that\'s got everything you want and more. Feel the satisfaction of every keystroke with world-renowned Cherry MX switches. Enjoy instant access to dedicated media keys on the upper left while gaming. And experience an unparalleled level of personalization with a customizable badge illuminated by Aura Sync RGB lighting. Boast your gaming flair as you dominate the battlefield.', 'peripherals', 'keyboards', 'rog-strix-flare.jpg', 164.49),
(45, 'ASUS H81M-P PLUS Intel H81 Micro ATX Motherboard Socket LGA1150', 'Media-renowned UEFI BIOS from Asus provides the smoothest mouse-controlled graphical BIOS, and now features more intuitive functions to quickly take you to your favourite BIOS pages and frequently-accessed settings through custom shortcuts. You can even write quick-notes in-BIOS for future reference, view in activity log of setting changes and modifications, and rename SATA ports. EZ Mode has a whole new look, upgraded with extra-friendly capabilities like detailed fan control, XMP profile settings, SATA information and fast clock adjustment. Together, these perfect your BIOS experience. ', 'components', 'motherboards', 'h81m-p.jpg', 68.99),
(46, 'ASUS CROSSHAIR VI HERO AMD X370 ATX Motherboard Socket AM4', 'For more than a decade, Republic of Gamers has delivered exemplary design and performance to thrill the world\'s best players and PC enthusiasts. Our journey is a road without end. Now, it\'s time for competitors to be warned and for gamers and enthusiasts to push the limits: The packed and pumped ROG Crosshair VI Hero Series motherboard is ready to defeat all challengers.', 'components', 'motherboards', 'crosshair-6-hero.jpg', 235.99),
(47, 'ASUS ROG STRIX X370-F GAMING AMD X370 ATX Gaming Motherboard Socket AM4', 'ROG Strix X370-F Gaming motherboards continue the proud legacy of the Pro Gaming series with acclaimed ROG innovations. ROG Strix X370-F Gaming motherboards combine bold aesthetic with premier performance and incredible audio to deliver unrelieved gaming experiences and style. Support for the latest AMD processors and technologies, plus exclusive ROG innovations, take performance to the next level to give you the edge against opponents. ROG Strix X370-F Gaming charges every movement of every game with thrilling energy and equips you with epic speed and agility. Join the Republic with ROG Strix X370-F Gaming and dominate your game! ', 'components', 'motherboards', 'rog-strix-x370f.jpg', 185.49),
(48, 'ASUS ROG STRIX Z370-H GAMING Intel Z370 ATX DDR4 GAMING Motherboard, LGA1151', 'One click takes care of all that complex tuning. ASUS 5-Way Optimisation makes your PC smart. It dynamically optimises essential aspects of the system, providing overclocking and cooling profiles that are tailored for your rig. ASUS OptiMem preserves memory signal integrity by routing memory traces and vias to the optimal PCB layer, and our T-Topology layout ensures time-aligned signaling by balancing trace lengths between memory slots. These enhancements lead to more headroom for overclocking and improved stability, allowing memory speeds of DDR4-4000 and beyond with all slots populated.', 'components', 'motherboards', 'rog-strix-7370h.jpg', 178.49),
(49, 'ASUS M5A78L-M PLUS USB3 Motherboard AMD 760G, Micro ATX, AM3+ Socket', 'This motherboard supports AMD AM3+ multi-core processors with unique cache delivers better overclocking capabilities and less power consumption. It features deal-channel DDR3 memory support and accelerates data transfer rate up to 5200MT/s via HyperTransport 3.0 based system bus. This motherboard also supports AMD CPUs in the new 32nm manufacturing process.  ', 'components', 'motherboards', 'm5a78l-m.jpg', 77.49),
(50, 'ASUS PRIME H270M-PLUS Intel H270 LGA1151 Micro ATX Motherboard ', 'ASUS Prime is the next evolution of ASUS motherboard, born of the pedigree that stretches back to 1989. Our team of world-class engineers are passionate about empowering everyone to enjoy the benefits of customisation and tuning, and the driving force behind the development of Prime is to make advances enthusiast controls easy accessible - maximising performance, stability and comparability for the very best DIY PC experiences. Simply stated: it\'s time for Prime!', 'components', 'motherboards', 'prime-h270m-plus.jpg', 102.99);

-- --------------------------------------------------------

--
-- Table structure for table `users`
--

DROP TABLE IF EXISTS `users`;
CREATE TABLE IF NOT EXISTS `users` (
  `user_id` int(11) NOT NULL AUTO_INCREMENT,
  `user_first` varchar(256) NOT NULL,
  `user_last` varchar(256) NOT NULL,
  `user_email` varchar(256) NOT NULL,
  `user_pwd` varchar(256) NOT NULL,
  PRIMARY KEY (`user_id`)
) ENGINE=MyISAM AUTO_INCREMENT=5 DEFAULT CHARSET=latin1;

--
-- Dumping data for table `users`
--

INSERT INTO `users` (`user_id`, `user_first`, `user_last`, `user_email`, `user_pwd`) VALUES
(1, 'Samuel', 'Barnes', 'barnes.samb@gmail.com', '$2y$10$uh4YCCgIFoFxOhU6YGcb7ugpUW8eNmFtQhyrd0.DtP71ypfzN2tUS'),
(2, 'test', 'test', 'test@test.com', '$2y$10$J3516TdSrEbp3alAhHyvT..2PGNWjo1ZOMxVlYTqgzLPTW3SP7h2a'),
(3, 'test', 'test', 'test1@mail.com', '$2y$10$0jGZ75n07lGeyHNJwtDb3.WZ4ivxWW8lp97jJEvhq9t3jXj33uXfW'),
(4, 'bob', 'bob', 'bob@bob.com', '$2y$10$u/WKsKgBCCIH1RZgAaNHJuBItx/d80oLmMxcMVlLDJAmSGKZAdMyS');
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
